"use client";
import { useMemo, useState } from 'react';
import { platforms, formats, isContentReady, isPublicationStep, localDate, monthDates, type WorkspaceData, type Content, type Publication, type Platform } from '@/lib/domain';
import { requireSupabase } from '@/lib/supabase/client';
import { addStep, reuseContent, savePublication, setStep } from '@/lib/supabase/workspace';
import { ErrorNotice, Modal, errorMessage, shortDate } from './ui';
import type { View } from '@/app/page';

type Props = { view: View; data: WorkspaceData; month: string; setMonth: (month: string) => void; refresh: () => Promise<void>; onContent: (content?: Content, publication?: Publication) => void; onCadence: () => void; onProjects: () => void; onImport: () => void };
export function Dashboard(props: Props) {
  const { data, view, month, setMonth } = props;
  const [projectFilter, setProjectFilter] = useState('');
  const [channel, setChannel] = useState('');
  const [query, setQuery] = useState('');
  const [scope, setScope] = useState('week');
  const [showFinished, setShowFinished] = useState(false);
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [bankAll, setBankAll] = useState(false);
  const today = localDate();
  const later = new Date(); later.setDate(later.getDate() + 7); const weekEnd = localDate(later);
  const byId = useMemo(() => new Map(data.contents.map(c => [c.id, c])), [data.contents]);
  const eligibleProjects = data.projects.filter(p => projectFilter ? p.id === projectFilter : p.status === 'active');
  const publications = data.publications.filter(p => eligibleProjects.some(project => project.id === p.project_id) && (!channel || p.platform === channel) && (!query || (byId.get(p.content_id || '')?.title || '').toLocaleLowerCase().includes(query.toLocaleLowerCase()))).sort((a, b) => a.planned_for.localeCompare(b.planned_for) || a.platform.localeCompare(b.platform));
  const visible = publications.filter(p => view === 'Plano mensal' ? p.planned_for.startsWith(month) && (!selectedDate || p.planned_for === selectedDate) : (scope === 'all' || (scope === 'today_only' ? p.planned_for === today : scope === 'today' ? p.planned_for <= today : p.planned_for <= weekEnd)) && (showFinished || !['scheduled', 'published'].includes(p.status)));
  const pendingCount = visible.filter(p => !['scheduled', 'published'].includes(p.status)).length;
  const bank = data.contents.filter(c => eligibleProjects.some(p => p.id === c.project_id) && (!query || c.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())) && (bankAll || isContentReady(c)));
  return <>
    {!data.projects.length ? <section className="empty-state panel"><p className="eyebrow">Bem-vinda à sua operação</p><h2>Organize vários produtos em uma só mesa.</h2><p>Cadastre um projeto ou importe um plano para começar. Você escolhe as redes, a frequência e as etapas de cada conteúdo.</p><div className="actions"><button className="primary" onClick={props.onProjects}>Criar meu primeiro projeto</button><button onClick={props.onImport}>Importar meu plano</button></div></section> : <>
    <div className="toolbar"><label>Projeto<select value={projectFilter} onChange={e => setProjectFilter(e.target.value)}><option value="">Todos os projetos ativos</option>{data.projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{view !== 'Banco de conteúdo' && <label>Rede<select value={channel} onChange={e => setChannel(e.target.value)}><option value="">Todas as redes</option>{Object.entries(platforms).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>}<label className="search-field">Buscar conteúdo<input type="search" placeholder="Título do conteúdo…" value={query} onChange={e => setQuery(e.target.value)} /></label>{view === 'Hoje' && <label>Horizonte<select value={scope} onChange={e => setScope(e.target.value)}><option value="today_only">Somente hoje</option><option value="week">Atrasados + próximos 7 dias</option><option value="today">Até hoje</option><option value="all">Todo o planejamento</option></select></label>}{view === 'Plano mensal' && <label>Mês<input type="month" required value={month} onChange={e => { if (e.target.value) { setMonth(e.target.value); setSelectedDate(null); } }} /></label>}</div>
    {view === 'Banco de conteúdo' ? <>
      <div className="section-heading"><div><p className="muted">Ativos prontos podem alimentar novas entregas sem repetir a produção. Os extras também ficam aqui.</p><label className="inline-check"><input type="checkbox" checked={bankAll} onChange={e => setBankAll(e.target.checked)} />Mostrar também conteúdos em preparação</label></div><button onClick={() => props.onContent()}>+ Criar conteúdo extra</button></div>
      {!bank.length && <p className="empty-state">Nenhum ativo {bankAll ? 'cadastrado neste filtro' : 'pronto ainda'}. Marque as etapas de produção ou cadastre um conteúdo extra.</p>}
      <div className="content-grid">{bank.map(content => <article className="panel bank-card" key={content.id}><p className="eyebrow">{data.projects.find(p => p.id === content.project_id)?.name} · {formats[content.type]}</p><h2>{content.title}</h2><p className="muted">{isContentReady(content) ? 'Produção pronta ✓' : 'Em preparação'} · {data.publications.filter(p => p.content_id === content.id).length} usos no calendário</p><button onClick={() => props.onContent(content)}>Abrir / editar</button><ReuseButton content={content} data={data} refresh={props.refresh} /></article>)}</div>
    </> : <>
      <div className="section-heading"><div>{view === 'Hoje' ? <><p><strong>{pendingCount} entregas precisam de trabalho</strong> no horizonte selecionado.</p><label className="inline-check"><input type="checkbox" checked={showFinished} onChange={e => setShowFinished(e.target.checked)} />Incluir agendadas e publicadas</label></> : <p className="muted">Selecione um dia para abrir os conteúdos e seus checklists.</p>}</div><div className="actions"><button onClick={props.onCadence}>Definir frequência</button><button onClick={() => props.onContent()}>+ Conteúdo</button></div></div>
      {view === 'Plano mensal' && <><div className="calendar-scroll"><div className="calendar">{['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'].map(d => <div key={d} className="calendar-label">{d}</div>)}{Array.from({ length: new Date(month + '-01T12:00:00').getDay() }, (_, i) => <div key={'blank' + i} />)}{monthDates(month).map(date => { const rows = publications.filter(p => p.planned_for === date); const ready = rows.filter(p => ['scheduled', 'published'].includes(p.status)).length; return <button key={date} className={'calendar-day ' + (selectedDate === date ? 'selected ' : '') + (date === today ? 'today' : '')} onClick={() => setSelectedDate(selectedDate === date ? null : date)}><strong>{Number(date.slice(-2))}</strong><span>{rows.length} entregas</span><small>{ready} agendadas/publicadas</small><div className="calendar-dots">{data.projects.filter(project => rows.some(p => p.project_id === project.id)).map(p => <i key={p.id} style={{ background: p.color || '#6756d9' }} title={p.name} />)}</div></button>; })}</div></div>{selectedDate && <div className="section-heading"><h2>{shortDate(selectedDate)}</h2><button onClick={() => setSelectedDate(null)}>Ver todo o mês</button></div>}</>}
      {!visible.length && <section className="empty-state panel"><h2>Nenhuma pendência neste filtro</h2><p>Amplie o horizonte para adiantar conteúdos ou importe o próximo plano.</p><button onClick={props.onImport}>Importar plano</button></section>}
      {eligibleProjects.map(project => { const rows = visible.filter(p => p.project_id === project.id); if (!rows.length) return null; return <details key={project.id} className="panel work-project"><summary className="project-heading" style={{ borderLeftColor: project.color || '#6756d9' }}><h2>{project.name}</h2><span>{rows.length} entregas <b aria-hidden="true">⌄</b></span></summary>{(Object.keys(platforms) as Platform[]).map(platform => { const channelRows = rows.filter(p => p.platform === platform); if (!channelRows.length) return null; return <div key={platform} className="channel-group"><h3>{platforms[platform]} <span>{channelRows.length}</span></h3>{channelRows.map(publication => <WorkRow key={publication.id} publication={publication} content={byId.get(publication.content_id || '')} data={data} refresh={props.refresh} onContent={props.onContent} />)}</div>; })}</details>; })}
    </>}
    </>}
  </>;
}

function WorkRow({ publication, content, data, refresh, onContent }: { publication: Publication; content?: Content; data: WorkspaceData; refresh: () => Promise<void>; onContent: Props['onContent'] }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const productionSteps = content?.steps.filter(s => !isPublicationStep(s)) || [];
  const required = productionSteps.filter(s => s.is_required); const done = required.filter(s => s.is_done).length;
  const deliveryDone = ['scheduled', 'published'].includes(publication.status);
  const next = required.find(s => !s.is_done)?.label;
  async function toggle(id: string, checked: boolean) { setBusy(true); setError(''); try { await setStep(requireSupabase(), id, checked); await refresh(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <details className="work-row"><summary><div className="row-title"><span className={'date-tag ' + (publication.planned_for < localDate() && !deliveryDone ? 'overdue' : '')}>{shortDate(publication.planned_for)}{publication.planned_for < localDate() && !deliveryDone ? ' · atraso' : ''}</span><strong>{content?.title || 'Escolher o conteúdo desta entrega'}</strong><small>{content ? formats[content.type] : publication.format || 'Formato a definir'} · {deliveryDone ? publication.status === 'published' ? 'Publicada' : 'Agendamento registrado' : next ? 'Próxima etapa: ' + next : content ? 'Produção pronta. Registrar agendamento ou publicação.' : 'Vincule um conteúdo pronto ou cadastre uma ideia.'}</small></div><div className="row-progress"><strong>{content ? done + '/' + required.length + ' produção' : 'Planejar'}</strong>{content && <progress value={done} max={required.length || 1} />}{deliveryDone && <span className="status-good">✓ {publication.status === 'published' ? 'Publicada' : 'Agendada'}</span>}<span aria-hidden="true">⌄</span></div></summary><div className="row-body"><ErrorNotice message={error} />{content ? <><div className="actions"><button onClick={() => onContent(content, publication)}>Editar conteúdo / links</button><ReuseButton content={content} data={data} refresh={refresh} /></div>{content.technical_reference && <p className="muted">Referência: {content.technical_reference}</p>}{Array.from(new Set(productionSteps.map(s => s.block))).map(block => <fieldset className="checklist-block" key={block}><legend>{block}</legend>{productionSteps.filter(s => s.block === block).map(step => <label className={step.is_done ? 'step done' : 'step'} key={step.id}><input type="checkbox" checked={step.is_done} disabled={busy} onChange={e => toggle(step.id, e.target.checked)} /><span>{step.label}{!step.is_required && <small> · opcional</small>}</span></label>)}</fieldset>)}<AddStep contentId={content.id} refresh={refresh} /><PublicationAction publication={publication} ready={isContentReady(content)} refresh={refresh} /></> : <div className="actions"><button className="primary" onClick={() => onContent(undefined, publication)}>Cadastrar ideia</button><ReuseButton data={data} target={publication} refresh={refresh} /></div>}</div></details>;
}

function AddStep({ contentId, refresh }: { contentId: string; refresh: () => Promise<void> }) {
  const [label, setLabel] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <form className="add-step" onSubmit={async e => { e.preventDefault(); setBusy(true); try { await addStep(requireSupabase(), contentId, label.trim(), true); setLabel(''); await refresh(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }}><input aria-label="Nova etapa" placeholder="Precisa de outra etapa? Escreva aqui…" value={label} maxLength={150} onChange={e => setLabel(e.target.value)} /><button disabled={busy || !label.trim()}>Adicionar etapa</button><ErrorNotice message={error} /></form>;
}
function PublicationAction({ publication, ready, refresh }: { publication: Publication; ready: boolean; refresh: () => Promise<void> }) {
  const [when, setWhen] = useState(publication.scheduled_for ? new Date(new Date(publication.scheduled_for).getTime() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16) : publication.planned_for + 'T18:00');
  const [url, setUrl] = useState(publication.publication_url || ''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function save(status: 'scheduled' | 'published' | 'in_progress') {
    setBusy(true); setError(''); try { await savePublication(requireSupabase(), publication, status, status === 'scheduled' ? new Date(when).toISOString() : undefined, url); await refresh(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); }
  }
  return <fieldset className="delivery"><legend>Publicação · {platforms[publication.platform]}</legend><p className="muted">Registre o que foi feito na rede. A produção compartilhada não publica os outros canais automaticamente.</p><div className="form-columns"><label>Data e hora do agendamento<input type="datetime-local" value={when} onChange={e => setWhen(e.target.value)} /></label><label>Link da publicação (opcional)<input type="url" value={url} placeholder="https://…" onChange={e => setUrl(e.target.value)} /></label></div><div className="actions"><button disabled={busy || !ready || !when} onClick={() => save('scheduled')}>Registrar agendamento</button><button disabled={busy} onClick={() => save('published')}>Marcar publicada</button>{['published', 'scheduled'].includes(publication.status) && <button disabled={busy} onClick={() => save('in_progress')}>Reabrir entrega</button>}</div>{!ready && <p className="muted">Conclua as etapas obrigatórias para registrar o agendamento. Se já publicou, pode registrar a publicação sem inventar checks passados.</p>}<ErrorNotice message={error} /></fieldset>;
}
export function ReuseButton({ content, data, target, refresh }: { content?: Content; data: WorkspaceData; target?: Publication; refresh: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [chosen, setChosen] = useState(content?.id || ''); const [platform, setPlatform] = useState<Platform>(target?.platform || 'instagram'); const [date, setDate] = useState(target?.planned_for || localDate()); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const available = data.contents.filter(c => isContentReady(c) && (!target || c.project_id === target.project_id));
  return <><button onClick={() => setOpen(true)}>{content ? 'Reutilizar' : 'Escolher do banco'}</button>{open && <Modal title="Reutilizar conteúdo pronto" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={async e => { e.preventDefault(); setBusy(true); try { const selected = data.contents.find(c => c.id === chosen); if (!selected) throw new Error('Selecione um conteúdo.'); await reuseContent(requireSupabase(), selected.id, selected.project_id, platform, date); await refresh(); setOpen(false); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }}><label>Conteúdo<select value={chosen} onChange={e => setChosen(e.target.value)} required><option value="">Selecione um ativo pronto</option>{available.map(c => <option key={c.id} value={c.id}>{c.title} · {formats[c.type]}</option>)}</select></label><label>Rede<select value={platform} disabled={!!target} onChange={e => setPlatform(e.target.value as Platform)}>{Object.entries(platforms).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Data<input type="date" required value={date} disabled={!!target} onChange={e => setDate(e.target.value)} /></label><p className="muted">O mesmo ativo alimenta a nova entrega. Os checks de produção são compartilhados; a publicação é independente por rede.</p><ErrorNotice message={error} /><button className="primary" disabled={busy || !chosen}>{busy ? 'Vinculando…' : 'Vincular à entrega'}</button></form></Modal>}</>;
}
